import Head from "next/head";
import React from "react";
import styles from "@/styles/Home.module.css";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

const About = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>
        <h1>About Page</h1>
        {/* <div> */}
          <p>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eligendi
            cupiditate nisi doloribus! Perspiciatis suscipit sed iure voluptatum
            vel eveniet odit, atque quae esse ducimus repellat similique, quia
            eos deserunt dolores eligendi. Qui atque quam quidem vel eligendi
            fuga nostrum reiciendis unde asperiores omnis tempore, ab assumenda
            explicabo minus eveniet! A ipsum dolores eius ducimus provident.
          </p>
        {/* </div> */}
      </main>
    </>
  );
};

export default About;
