import Head from "next/head";
import React from "react";
import styles from "@/styles/Home.module.css";
import { Inter } from "next/font/google";
import { useBlogContext } from "../components/blogContext";
import { Box, Toolbar, Typography } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

const SingleBlog = () => {
  const { selectedBlog } = useBlogContext();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>
        {/* Display the retrieved blog data */}
        {selectedBlog && (
          <>
            {/* <p>Tittle: {selectedBlog.tittle}</p> */}
            {/* <p>Description: {selectedBlog.descreption}</p> */}
            <Box component="main" sx={{ p: 3 }}>
              <Toolbar />
              <Typography variant="h4" gutterBottom>
                {selectedBlog.tittle} :
              </Typography>
              <Typography>{selectedBlog.descreption}</Typography>
            </Box>
          </>
        )}
      </main>
    </>
  );
};

export default SingleBlog;
