import * as React from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Card from "../components/homeCard";
import Upload from "../components/blogUpload";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [blogs, setBlogs] = React.useState([]);

  const fetchdata = async () => {
    try {
      const response = await fetch("/api/blogs");
      if (!response.ok) {
        throw new Error(
          `statusCode ${response.status}- ${response.statusText}`
        );
      }
      const data = await response.json();
      setBlogs(data);
    } catch (error) {
      console.log(error.message);
    }
  };

  React.useEffect(() => {
    fetchdata();
  }, []);

 
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>
        {/* <Upload /> */}
        {blogs.map((blog) => (
        
          <Card
            key={blog.id}
            tittle={blog.Tittle}
            descreption={blog.Descreption}
            blogId = {blog.BlogID}
          />
        ))}

      </main>
    </>
  );
}
